"""
Takes the all_analysis_results.csv file generated by analyze_docids.py and produces plots to visualize the results.
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.cm as cm
from matplotlib.colors import Normalize
from matplotlib.lines import Line2D
from matplotlib.patches import Patch



def create_comprehensive_plot(df_analysis: pd.DataFrame, df_ir: pd.DataFrame, output_dir: str, uniqueness=True):
    """
    Create a comprehensive figure with dynamically determined rows based on available metrics.
    Columns: R@1, R@10, MRR@10
    """
    # Define mapping from CSV column names to cleaner display names
    METRIC_DISPLAY_NAMES = {
        'uniqueness_ratio': 'U',
        'mean_entropy': 'Entropy',
        'mean_gini': 'Gini',
        'correlation_hierarchical': 'Ssem (Hier)',
        'correlation_full': 'Ssem (Full)',
        'correlation_mix': 'Ssem (Mix)',
        'mean_hierarchical_shared_sim': 'Shared Sim (Hier)',
        'mean_full_shared_sim': 'Shared Sim (Full)',
        'mean_mix_shared_sim': 'Shared Sim (Mix)',
        'ranking_preservation_hierarchical': 'A (Hier)',
        'ranking_preservation_full': 'A (Full)',
        'ranking_preservation_mix': 'A (Mix)',
        'agreement_query_pos_hierarchical': 'A_ir (Hier)',
        'agreement_query_pos_full': 'A_ir (Full)',
        'agreement_query_pos_mix': 'A_ir (Mix)',
        'agreement_query_pos_hierarchical_no_ties': 'A_ir_no_ties (Hier)',
        'agreement_query_pos_full_no_ties': 'A_ir_no_ties (Full)',
        'agreement_query_pos_mix_no_ties': 'A_ir_no_ties (Mix)',
        'r_hier': 'R (Hier)',
        'r_full': 'R (Full)',
        'r_mix': 'R (Mix)',
        'robustness_sim_hierarchical': 'Robust Sim (Hier)',
        'robustness_sim_full': 'Robust Sim (Full)',
        'robustness_sim_mix': 'Robust Sim (Mix)',
        'robustness_ranking_preservation_hierarchical': 'Robust A (Hier)',
        'robustness_ranking_preservation_full': 'Robust A (Full)',
        'robustness_ranking_preservation_mix': 'Robust A (Mix)',
    }
    
    # Merge the two dataframes on encoding method, num_codebooks, codebook_size, and nb_subspaces
    df_analysis['num_codebooks'] = df_analysis['num_codebooks'].astype(int)
    df_analysis['codebook_size'] = df_analysis['codebook_size'].astype(int)
    df_ir['num_codebooks'] = df_ir['num_codebooks'].astype(int)
    df_ir['codebook_size'] = df_ir['codebook_size'].astype(int)
    if 'nb_subspaces' in df_analysis.columns and 'nb_subspaces' in df_ir.columns:
        df_analysis['nb_subspaces'] = df_analysis['nb_subspaces'].astype(int)
        df_ir['nb_subspaces'] = df_ir['nb_subspaces'].astype(int)
        df_merged = pd.merge(df_analysis, df_ir, on=['encoding', 'num_codebooks', 'codebook_size', 'nb_subspaces'])
    else:
        df_merged = pd.merge(df_analysis, df_ir, on=['encoding', 'num_codebooks', 'codebook_size'])
    
    # Compute average of min and max for IR metrics
    df_merged['R@1_avg'] = (df_merged['R@1_worst'] + df_merged['R@1_best']) / 2
    df_merged['R@10_avg'] = (df_merged['R@10_worst'] + df_merged['R@10_best']) / 2
    df_merged['MRR@10_avg'] = (df_merged['MRR@10_worst'] + df_merged['MRR@10_best']) / 2

    if 'nb_subspaces' in df_merged.columns:
        df_merged['docid_length'] = df_merged['num_codebooks'] * df_merged['nb_subspaces']
    
    # Determine which metrics are available in the dataframe
    available_metrics = []
    available_labels = []
    
    # Check each metric and add if it exists in the dataframe
    for metric_col, display_name in METRIC_DISPLAY_NAMES.items():
        if metric_col in df_merged.columns:
            # check that at least one value is not NaN
            if df_merged[metric_col].notna().any():
                if uniqueness and metric_col != 'uniqueness_ratio' and metric_col != 'mean_entropy' and metric_col != 'mean_gini':
                    # Create weighted metric
                    weighted_col = f'U*{display_name}'
                    df_merged[weighted_col] = df_merged['uniqueness_ratio'] * df_merged[metric_col]
                    available_metrics.append(weighted_col)
                    available_labels.append(f'U × {display_name}')
                else:
                    # Use metric as-is
                    available_metrics.append(metric_col)
                    available_labels.append(display_name)
    
    if not available_metrics:
        print("No metrics available to plot!")
        return
    
    print(f"Available metrics to plot: {len(available_metrics)}")
    for metric, label in zip(available_metrics, available_labels):
        print(f"  - {label} ({metric})")
    
    # Use the dynamically determined metrics
    analysis_metrics = available_metrics
    analysis_labels = available_labels
    
    ir_metrics = ['R@1_avg', 'R@10_avg', 'MRR@10_avg']
    ir_labels = ['R@1', 'R@10', 'MRR@10']
    
    # Create figure with subplots
    for encoding in df_merged['encoding'].unique():
        df_encoding = df_merged[df_merged['encoding'] == encoding]

        # Ensure axes is always 2D
        if len(analysis_metrics) == 1:
            fig, axes = plt.subplots(1, 3, figsize=(18, 4))
            axes = axes.reshape(1, -1)
        else:
            fig, axes = plt.subplots(len(analysis_metrics), 3, figsize=(18, len(analysis_metrics)*4))
            if len(analysis_metrics) > 1:
                axes = axes.reshape(len(analysis_metrics), 3)
        if uniqueness:
            fig.suptitle(f'Analysis Metrics (weighted by Uniqueness) vs IR Performance Metrics, for {encoding}', fontsize=16, y=0.995)
        else:
            fig.suptitle(f'Analysis Metrics vs IR Performance Metrics, for {encoding}', fontsize=16, y=0.995)

        # Iterate through each subplot
        for i, (analysis_metric, analysis_label) in enumerate(zip(analysis_metrics, analysis_labels)):
            for j, (ir_metric, ir_label) in enumerate(zip(ir_metrics, ir_labels)):
                ax = axes[i, j]
                
                # Create scatter plot
                if 'docid_length' in df_encoding.columns:
                    sns.scatterplot(
                        data=df_encoding, 
                        x=analysis_metric, 
                        y=ir_metric, 
                        hue='docid_length',
                        style='codebook_size',
                        ax=ax,
                        alpha=0.7
                    )
                else:
                    sns.scatterplot(
                        data=df_encoding, 
                        x=analysis_metric, 
                        y=ir_metric, 
                        hue='num_codebooks',
                        style='codebook_size',
                        ax=ax,
                        alpha=0.7
                    )
                
                # Set titles and labels
                if i == 0:
                    ax.set_title(ir_label, fontsize=12, fontweight='bold')
                else:
                    ax.set_title('')
                
                ax.set_ylabel(ir_label, fontsize=10)

                
                # Add row labels on the left
                if j == 0:
                    # Add text annotation on the left side
                    ax.text(-0.3, 0.5, analysis_label, transform=ax.transAxes, 
                        fontsize=11, fontweight='bold', va='center', ha='right')
                
                # Add grid
                ax.grid(True, alpha=0.3)
                
                # Handle legend - only show on the first subplot
                if i == 0 and j == 2:
                    ax.legend(title='(DocID Length, V)', bbox_to_anchor=(1.05, 1), loc='upper left')
                else:
                    ax.get_legend().remove() if ax.get_legend() else None
        
        # Adjust layout
        plt.tight_layout(rect=[0, 0, 1, 0.995])
        
        # Save the plot
        if uniqueness:
            output_path = os.path.join(output_dir, f"comprehensive_analysis_vs_ir_avg_uniqueness_{encoding}.png")
        else:
            output_path = os.path.join(output_dir, f"comprehensive_analysis_vs_ir_avg_{encoding}.png")
        
        plt.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"Comprehensive plot saved to {output_path}")
        plt.close()
    

    # then everything in the same graph
    # Map encoding names to display names
    encoding_map = {
        'pq': 'PQ',
        'rq-kmeans': 'R-Kmeans',
        'rq-module': 'R-VQ',
        'pq-rq': 'PRQ'
    }
    df_merged['encoding_display'] = df_merged['encoding'].map(encoding_map).fillna(df_merged['encoding'])
    
    fig, axes = plt.subplots(len(analysis_metrics), 3, figsize=(18, len(analysis_metrics)*4))
    if uniqueness:
        fig.suptitle(f'Analysis Metrics (weighted by Uniqueness) vs IR Performance Metrics, for all encodings', fontsize=16, y=0.995)
    else:
        fig.suptitle(f'Analysis Metrics vs IR Performance Metrics, for all encodings', fontsize=16, y=0.995)
    
    # Iterate through each subplot
    for i, (analysis_metric, analysis_label) in enumerate(zip(analysis_metrics, analysis_labels)):
        for j, (ir_metric, ir_label) in enumerate(zip(ir_metrics, ir_labels)):
            ax = axes[i, j]
            
            # Create scatter plot
            sns.scatterplot(
                data=df_merged, 
                x=analysis_metric, 
                y=ir_metric, 
                hue='encoding_display',
                ax=ax,
                alpha=0.7
            )
            
            # Set titles and labels
            if i == 0:
                ax.set_title(ir_label, fontsize=12, fontweight='bold')
            else:
                ax.set_title('')
            
            ax.set_ylabel(ir_label, fontsize=10)
            
            
            # Add row labels on the left
            if j == 0:
                # Add text annotation on the left side
                ax.text(-0.3, 0.5, analysis_label, transform=ax.transAxes, 
                       fontsize=11, fontweight='bold', va='center', ha='right')
            
            # Add grid
            ax.grid(True, alpha=0.3)
            
            # Handle legend - only show on the first subplot
            if i == 0 and j == 2:
                ax.legend(title='Encoding', bbox_to_anchor=(1.05, 1), loc='upper left')
            else:
                ax.get_legend().remove() if ax.get_legend() else None
    
    # Adjust layout
    plt.tight_layout(rect=[0, 0, 1, 0.995])
    
    # Save the plot
    if uniqueness:
        output_path = os.path.join(output_dir, "comprehensive_analysis_vs_ir_avg_uniqueness.png")
    else:
        output_path = os.path.join(output_dir, "comprehensive_analysis_vs_ir_avg.png")
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Comprehensive plot saved to {output_path}")
    plt.close()


def create_individual_publication_plots(df_analysis: pd.DataFrame, df_ir: pd.DataFrame, output_dir: str):
    """
    Create 8 individual plots for publication:
    1. MRR@10 vs Uniqueness
    2. MRR@10 vs Entropy
    3. MRR@10 vs Shared Sim (Full) - with regression
    4. MRR@10 vs Shared Sim (Hier) - with regression
    5. MRR@10 vs Shared Sim (Mix) - with regression
    6. MRR@10 vs A (Full) - with regression
    7. MRR@10 vs A (Hier) - with regression
    8. MRR@10 vs A (Mix) - with regression
    
    For plots 3-8: filter points with uniqueness >= 0.9, show excluded points in grey,
    fit linear regression, and include R² in filename.
    """
    # Merge the dataframes
    df_analysis['num_codebooks'] = df_analysis['num_codebooks'].astype(int)
    df_analysis['codebook_size'] = df_analysis['codebook_size'].astype(int)
    df_ir['num_codebooks'] = df_ir['num_codebooks'].astype(int)
    df_ir['codebook_size'] = df_ir['codebook_size'].astype(int)
    
    if 'nb_subspaces' in df_analysis.columns and 'nb_subspaces' in df_ir.columns:
        df_analysis['nb_subspaces'] = df_analysis['nb_subspaces'].astype(int)
        df_ir['nb_subspaces'] = df_ir['nb_subspaces'].astype(int)
        df_merged = pd.merge(df_analysis, df_ir, on=['encoding', 'num_codebooks', 'codebook_size', 'nb_subspaces'])
    else:
        df_merged = pd.merge(df_analysis, df_ir, on=['encoding', 'num_codebooks', 'codebook_size'])
    
    # Compute average of min and max for IR metrics
    df_merged['MRR@10_avg'] = (df_merged['MRR@10_worst'] + df_merged['MRR@10_best']) / 2
    
    # Map encoding names to display names and marker styles
    encoding_map = {
        'pq': 'PQ',
        'rq-kmeans': 'R-Kmeans',
        'rq-module': 'R-VQ',
        'pq-rq': 'PRQ'
    }
    df_merged['encoding_display'] = df_merged['encoding'].map(encoding_map).fillna(df_merged['encoding'])
    
    # Define marker styles for each encoding
    marker_map = {
        'PQ': 'o',        # hollow circle (donut)
        'R-Kmeans': '+',  # plus
        'R-VQ': '*',      # star
        'PRQ': 'x'        # x mark
    }
    
    
    # Create color map for encoding methods
    encoding_colors = {
        'PQ': '#1f77b4',      # blue
        'R-Kmeans': '#ff7f0e', # orange
        'R-VQ': '#2ca02c',     # green
        'PRQ': '#d62728'       # red
    }
    
    # Define the 8 plots
    plots = [
        {'x_col': 'uniqueness_ratio', 'x_label': 'Uniqueness', 'use_regression': False, 'filter_data': False},
        {'x_col': 'mean_entropy', 'x_label': 'Entropy', 'use_regression': False, 'filter_data': False},
        {'x_col': 'mean_full_shared_sim', 'x_label': 'Shared Similarity (Full)', 'use_regression': True, 'filter_data': False},
        {'x_col': 'mean_hierarchical_shared_sim', 'x_label': 'Shared Similarity (Hierarchical)', 'use_regression': True, 'filter_data': False},
        {'x_col': 'mean_mix_shared_sim', 'x_label': 'Shared Similarity', 'use_regression': True, 'filter_data': False},
        {'x_col': 'ranking_preservation_full', 'x_label': 'A (Full)', 'use_regression': True, 'filter_data': True},
        {'x_col': 'ranking_preservation_hierarchical', 'x_label': 'A (Hierarchical)', 'use_regression': True, 'filter_data': True},
        {'x_col': 'ranking_preservation_mix', 'x_label': 'A', 'use_regression': True, 'filter_data': True},
    ]
    
    for plot_config in plots:
        x_col = plot_config['x_col']
        x_label = plot_config['x_label']
        use_regression = plot_config['use_regression']
        filter_data = plot_config['filter_data']
        
        fig, ax = plt.subplots(figsize=(8, 6))
        
        if filter_data:
            # Filter data: uniqueness >= 0.9 for regression
            df_high_uniq = df_merged[df_merged['uniqueness_ratio'] >= 0.9].copy()
            df_low_uniq = df_merged[df_merged['uniqueness_ratio'] < 0.9].copy()
            
            # Plot excluded points in grey first
            for _, row in df_low_uniq.iterrows():
                ax.scatter(
                    row[x_col], 
                    row['MRR@10_avg'],
                    marker='o',
                    s=100,
                    facecolors='lightgrey',
                    edgecolors='grey',
                    linewidths=1,
                    alpha=0.3
                )
            
            # Plot included points with colors
            for _, row in df_high_uniq.iterrows():
                encoding_display = row['encoding_display']
                color = encoding_colors.get(encoding_display, 'black')
                marker = marker_map.get(encoding_display, 'o')
                
                if marker == 'o':  # hollow circle for PQ
                    ax.scatter(
                        row[x_col], 
                        row['MRR@10_avg'],
                        marker='o',
                        s=120,
                        facecolors='none',
                        edgecolors=color,
                        linewidths=2,
                        alpha=0.8
                    )
                else:  # +, *, x for other encodings
                    ax.scatter(
                        row[x_col], 
                        row['MRR@10_avg'],
                        marker=marker,
                        s=150,
                        c=color,
                        alpha=0.8
                    )
            
            # Use filtered data for regression
            df_for_regression = df_high_uniq
        else:
            # No filtering - plot all points
            df_for_regression = df_merged
            for _, row in df_merged.iterrows():
                encoding_display = row['encoding_display']
                color = encoding_colors.get(encoding_display, 'black')
                marker = marker_map.get(encoding_display, 'o')
                
                if marker == 'o':  # hollow circle for PQ
                    ax.scatter(
                        row[x_col], 
                        row['MRR@10_avg'],
                        marker='o',
                        s=120,
                        facecolors='none',
                        edgecolors=color,
                        linewidths=2,
                        alpha=0.8
                    )
                else:  # +, *, x for other encodings
                    ax.scatter(
                        row[x_col], 
                        row['MRR@10_avg'],
                        marker=marker,
                        s=120,
                        c=color,
                        alpha=0.8
                    )
        
        # Fit linear regression if requested
        if use_regression:
            if len(df_for_regression) > 1:
                X = df_for_regression[x_col].values.reshape(-1, 1)
                y = df_for_regression['MRR@10_avg'].values
                
                # Remove NaN values
                valid_mask = ~(np.isnan(X.flatten()) | np.isnan(y))
                X_valid = X[valid_mask]
                y_valid = y[valid_mask]
                
                if len(X_valid) > 1:
                    model = LinearRegression()
                    model.fit(X_valid, y_valid)
                    y_pred = model.predict(X_valid)
                    r2 = r2_score(y_valid, y_pred)
                    
                    # Plot regression line
                    x_range = np.linspace(X_valid.min(), X_valid.max(), 100).reshape(-1, 1)
                    y_range = model.predict(x_range)
                    ax.plot(x_range, y_range, 'r--', linewidth=2, label=f'Linear fit (R² = {r2:.3f})')
                    
                    # Add text with R² on the plot
                    if filter_data:
                        ax.text(0.05, 0.95, f'R² = {r2:.3f}\n(U ≥ 0.9)', 
                               transform=ax.transAxes, fontsize=14, verticalalignment='top',
                               bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
                    else:
                        ax.text(0.05, 0.95, f'R² = {r2:.3f}', 
                               transform=ax.transAxes, fontsize=14, verticalalignment='top',
                               bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
                else:
                    r2 = 0.0
            else:
                r2 = 0.0
        else:
            r2 = None
        
        # Set labels and title
        ax.set_xlabel(x_label, fontsize=25, fontweight='bold')
        ax.set_ylabel('MRR@10', fontsize=25, fontweight='bold')
        ax.set_title(f'MRR@10 vs {x_label}', fontsize=25, fontweight='bold')
        ax.tick_params(axis='both', which='major', labelsize=20)
        ax.grid(True, alpha=0.3)
        
        # Create custom legend
        legend_elements = []
        
        # Encoding with colors and markers
        for enc in ['PQ', 'R-Kmeans', 'R-VQ', 'PRQ']:
            color = encoding_colors.get(enc, 'gray')
            marker = marker_map.get(enc, 'o')
            
            if marker == 'o':  # hollow circle for PQ
                legend_elements.append(Line2D([0], [0], marker='o', 
                                             markerfacecolor='none',
                                             markeredgecolor=color,
                                             markeredgewidth=2,
                                             linestyle='', markersize=10,
                                             label=enc))
            else:  # +, *, x for other encodings
                legend_elements.append(Line2D([0], [0], marker=marker, color=color, 
                                             markerfacecolor=color,
                                             linestyle='', markersize=10,
                                             label=enc))
        
        # if use_regression:
        #     legend_elements.append(Line2D([0], [0], color='red', linestyle='--', linewidth=2, label='Linear fit'))
        
        ax.legend(handles=legend_elements, loc='best', fontsize=23, ncol=1)
        
        plt.tight_layout()
        
        # Save the plot
        x_label_clean = x_label.replace(' ', '_').replace('(', '').replace(')', '').lower()
        if r2 is not None:
            output_path = os.path.join(output_dir, f"mrr10_vs_{x_label_clean}_r2_{r2:.3f}.png")
        else:
            output_path = os.path.join(output_dir, f"mrr10_vs_{x_label_clean}.png")
        
        plt.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"Publication plot saved to {output_path}")
        plt.close()



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Plot analysis results for docid encodings.")
    parser.add_argument("--analysis_results", type=str, required=True, help="Path to the all_analysis_results.csv file")
    parser.add_argument("--ir_results", type=str, required=True, help="Path to the IR evaluation results CSV file")
    parser.add_argument("--output_dir", type=str, default="./plots/new_plots", help="Directory to save the generated plots")
    
    args = parser.parse_args()
    
    df_analysis = pd.read_csv(args.analysis_results)
    df_ir = pd.read_csv(args.ir_results)

    os.makedirs(args.output_dir, exist_ok=True)

    
    # Create comprehensive plot with all metrics
    create_comprehensive_plot(
        df_analysis=df_analysis,
        df_ir=df_ir,
        output_dir=args.output_dir,
        uniqueness=True
    )
    create_comprehensive_plot(
        df_analysis=df_analysis,
        df_ir=df_ir,
        output_dir=args.output_dir,
        uniqueness=False
    )
    
    # Create individual publication plots
    # create_individual_publication_plots(
    #     df_analysis=df_analysis,
    #     df_ir=df_ir,
    #     output_dir=args.output_dir
    # )